---
title: "ADS506ProjectCode"
author: "Shrey Thaker"
date: "2025-11-18"
output: pdf_document
---

#EDA

```{r}
library(tidyverse)
library(tsibble)
library(lubridate)
library(fabletools)
library(feasts)
library(fpp3)

csv_path <- "C:/Users/shrey/Downloads/MRTSSM4481USN.csv"

clothing <- read_csv(csv_path, show_col_types = FALSE) |>
  select(date, Sales = value) |>
  mutate(Month = yearmonth(date)) |>
  as_tsibble(index = Month)
```

```{r}
clothing |> 
  summarise(
    Start = min(Month),
    End = max(Month),
    Min_Sales = min(Sales),
    Max_Sales = max(Sales),
    N = n()
  )
```

```{r}
autoplot(clothing, Sales) +
  labs(title = "Clothing Stores (MRTSSM4481USN) – Monthly Retail Sales",
       y = "Sales (US$)",
       x = "Year")
```

```{r}
clothing |>
  model(STL(Sales ~ trend() + season())) |>
  components() |>
  autoplot() +
  labs(title = "STL Decomposition – Clothing Store Sales")
```

```{r}
# Missing values
sum(is.na(clothing$Sales))

# Negative values
sum(clothing$Sales < 0)
```

#Model Development/Forecasting
```{r}
library(fpp3)
csv_path <- "C:/Users/shrey/Downloads/MRTSSM4481USN.csv"

clothing <- read_csv(csv_path, show_col_types = FALSE) |>
  select(date, Sales = value) |>
  mutate(Month = yearmonth(date)) |>
  as_tsibble(index = Month)

clothing |>
  gg_season(Sales, period = "year") +
  labs(title = "Seasonal Plot – Clothing Store Sales",
       y = "Sales (US$)")
```

```{r}
H <- 24
N <- nrow(clothing)

clothing_train <- clothing |> slice_head(n = N - H)
clothing_test  <- clothing |> slice_tail(n = H)
```

```{r}
fits_clothing <- clothing_train |>
  model(
    ETS_auto = ETS(Sales),
    TSLM_lin = TSLM(Sales ~ trend() + season())
  )

fc_clothing <- fits_clothing |>
  forecast(h = H)

acc_clothing <- fc_clothing |>
  accuracy(clothing_test) |>
  filter(.type == "Test") |>
  arrange(RMSE)

acc_clothing
```

```{r}
clothing |>
  autoplot(Sales) +
  autolayer(fc_clothing |> filter(.model == "ETS_auto"),
            level = c(80, 95),
            alpha = 0.6, size = 0.9) +
  labs(title = "Clothing Store Sales Forecast – ETS Model",
       x = "Date",
       y = "Sales (US$)") +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    plot.margin = margin(t = 25, r = 20, b = 10, l = 50),
    plot.title.position = "panel",
    legend.position = "right"
  )
```


